language: android
ajdk:
  - oraclejdk8
sudo: false
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository
    - android-19
script:
  - ./gradlew build connectedCheck
before_install:
  - chmod +x gradlew
branches:
  only:
    - TravisCI
