language: android
ajdk:
  - oraclejdk8
sudo:
ndroid:
  components:
    - tools
    - platform-tools
    - android-19
    - build-tools-25.0.2
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository
script:
  - ./gradlew build connectedCheck
before_install:
  - chmod +x gradlew
branches:
  only:
    - TravisCI
