language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-19
    - extra-google-m2repository
    - extra-android-m2repository
jdk:
  - oraclejdk8
script:
  - ./gradlew build connectedCheck
