language: android
jdk:
  - oraclejdk8
sudo: false
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository
    - android-25
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
script:
  - ./gradlew build connectedCheck
before_install:
  - chmod +x gradlew
branches:
  only:
    - TravisCI
